name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    name: "Unit Tests (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
        - 2.5
        - 2.7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Install HTML Tidy
        run: |
          wget https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-5.8.0-Linux-64bit.deb
          sudo dpkg -i tidy-5.8.0-Linux-64bit.deb
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Execute tests
        run:  bundle exec rake
